Merge upstream 5.15.3
stlehmann/PyQt5-stubs pull request #138
Opened 2021-02-26 05:09 UTC by altendky

Draft for:
- [ ] Actually merging #137
- [ ] Update merge from the `upstream` branch to here
- [ ] Self review of the net changes.

2021-02-27 03:35 UTC, altendky commented
I'm not exactly sure how I feel about dropping testing for 3.5.  But, we won't be getting 5.15.3 in 3.5 and we won't pass stubtest in both 5.15.3 and 5.15.2 (or probably really any two versions since some interface presumably changed).  So, I'm not really sure what it would mean to support multiple versions.  If it were a Python version issue you can do some amount of `if sys.version_info >= (3, 7):` and such.  But for the PyQt version I think we would have to either make a plugin or use `--always-true PYQT_5_15_2` or such and then our users would have to configure the same when running Mypy.  And that doesn't start into stubtest either...

2021-02-27 06:30 UTC, BryceBeagle commented
3.5 [has reached EOL](https://www.python.org/downloads/release/python-3510/). I'm fine dropping support for it

2021-03-03 05:00 UTC, BryceBeagle requested changes
What an absolutely riveting PR/changelist haha

I went through everything and it looks like a couple enums were missed. I wasn't able to verify the QtWebkit stuff*, but I'd assume the pattern holds

\* Do you know which PyPI package QtWebkit is in? I couldn't locate it

2021-03-03 05:00 UTC, BryceBeagle commented on PyQt5-stubs/Qt3DCore.pyi
> +    AllChanges = ... # type: ChangeFlag
Missing module-level versions

2021-03-03 05:00 UTC, BryceBeagle commented on PyQt5-stubs/QtCore.pyi
> +    QtInfoMsg = ... # type: QtMsgType
Missing module-level versions

2021-03-03 05:00 UTC, BryceBeagle commented on PyQt5-stubs/QtWebKit.pyi
> +        ComputedStyle = ... # type: QWebElement.StyleResolveStrategy
I would assume these are missing from the containing class too.

2021-03-03 05:00 UTC, BryceBeagle commented on PyQt5-stubs/QtWebKit.pyi
> +        DisallowSubdomains = ... # type: QWebSecurityOrigin.SubdomainSetting
I would assume these are missing from the containing class too.

2021-03-03 05:00 UTC, BryceBeagle commented on PyQt5-stubs/QtWebKit.pyi
> +        FantasyFont = ... # type: QWebSettings.FontFamily
I would assume these are missing from the containing class too.

2021-03-03 08:59 UTC, The-Compiler commented on PyQt5-stubs/QtWebKit.pyi
> +        FantasyFont = ... # type: QWebSettings.FontFamily
Indeed - to clarify, not just `FontFamily`, but also `WebAttribute` and probably the others.

2021-03-03 10:02 UTC, The-Compiler commented
> * Do you know which PyPI package QtWebkit is in? I couldn't locate it

It's not on PyPI - given that it was [removed from Qt 5.6](https://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules) but still (barely) [maintained independently](https://github.com/qtwebkit/qtwebkit), it's pretty much on "life support" in PyQt5. It only works when building PyQt5 from source with QtWebKit available (or when using distribution packages which do so).

It seems to be gone entirely in PyQt6 FWIW.

2021-03-03 15:21 UTC, altendky commented
Huh, I wonder what's up with stubtest missing these.  I thought it had caught such stuff.  Thanks for the review, I'll see what I can figure out.

2021-03-04 02:40 UTC, altendky commented
I guess it only catches stuff in the stubs that isn't in the runtime.  The other way could be pretty noise I suppose.  It's not like you want to hint the presence of `sys` or other misc 'not-exported' attributes in every stub etc.

2021-03-05 06:15 UTC, BryceBeagle approved these changes

2021-03-05 14:24 UTC, merged