Qscrollarea widgetresizeable
stlehmann/PyQt5-stubs pull request #188
Opened 2022-01-03 15:45 UTC by bluebird75

Finish the job started in #147 with simpler gui-less approach

2022-01-16 15:35 UTC, altendky commented
Is the plan to allow PRs that piecemeal add the dozens of parameters that PyQt adds to the constructor for the properties?

2022-01-17 20:14 UTC, bluebird75 commented
There is a grand plan for adding all properties and signals to the constructor of all QObject derived classes. But this is a huge plan. In the meantime, a user suggested this valid improvement, I'm all for taking it in. More examples are always a good thing in any case.

2022-01-17 21:53 UTC, altendky requested changes
I think the application creation can be dropped once https://github.com/python-qt-tools/PyQt5-stubs/pull/166 goes in, then this looks good.

2022-03-13 14:36 UTC, altendky approved these changes

2022-03-13 14:36 UTC, altendky commented on CHANGELOG.md
> +    `objectName` parameter to `QGroupBox.__init__()` .
I would tend to make all text, at least outside of Python code, use semantic newlines.

```suggestion
* [#148](https://github.com/python-qt-tools/PyQt5-stubs/pull/148) add `widgetResizable` parameter to `QScrollArea.__init__()` and `objectName` parameter to `QGroupBox.__init__()`.
```

2022-03-14 20:39 UTC, merged