Use @staticmethod consistently for any given @overload
stlehmann/PyQt5-stubs pull request #76
Opened 2020-09-23 13:28 UTC by altendky

2020-09-24 07:09 UTC, BryceBeagle requested changes
None of these functions now marked as static are actually static. Two of the methods changed to static do seem to have erroneous already-static methods that don't really exist (I left a comment).

See here for current understanding: https://github.com/stlehmann/PyQt5-stubs/blob/master/issues.md#1-mixed-overloads-with-static-and-non-static-methods

2020-09-24 07:09 UTC, BryceBeagle commented on PyQt5-stubs/QtTest.pyi
> -    def keySequence(self, widget: QtWidgets.QWidget, keySequence: typing.Union[QtGui.QKeySequence, QtGui.QKeySequence.StandardKey, str, int]) -> None: ...
I think the two already staticmethods should be removed. There's no static version according to the Qt docs:
https://doc.qt.io/qt-5/qtest.html#keySequence

2020-09-24 13:55 UTC, altendky commented
Well, I definitely glossed over this one.  In my head it was just an odd way to write the method without `self`.  Thanks for catching this and explaining and I'll review more carefully.

2020-09-25 03:29 UTC, BryceBeagle approved these changes

2020-09-25 03:30 UTC, BryceBeagle commented
We might want to change the `issues.md` to say to use `# type: ignore[misc]` and backport the other changes to add the `misc` too? For consistency?

2020-09-25 17:43 UTC, merged